#### PRODUCTS
GET http://localhost:8080/smartpackaging/api/products/
Accept: application/json

###
POST http://localhost:8080/smartpackaging/api/products/
Content-Type: application/json

{
  "id": 12,
  "name": "postedProd",
  "date": "2020-02-03",
  "weight": 12.2,
  "ingredients": "abc dce efg"
}

###
PUT http://localhost:8080/smartpackaging/api/products/1
Content-Type: application/json

{
  "id": 1,
  "name": "updatedNammmmme",
  "date": "2033-02-03",
  "weight": 32.2,
  "ingredients": "apple silicon"
}

###
DELETE http://localhost:8080/smartpackaging/api/products/12
Content-Type: application/json


#### SMARTPACKAGES
GET http://localhost:8080/smartpackaging/api/smartpackages/
Accept: application/json

###
POST http://localhost:8080/smartpackaging/api/smartpackages/
Content-Type: application/json

{
  "id": 3,
  "packType": "PRIMARY",
  "material": "cartao",
  "productId": 3
}

###
PUT http://localhost:8080/smartpackaging/api/smartpackages/1
Content-Type: application/json

{
  "id": 1,
  "packType": "SECONDARY",
  "material": "testing",
  "productId": 1,
  "currentTemperature": 40,
  "currentHumidity": 90,
  "currentAtmPressure": 80,
  "maxGForce": 10
}

###
DELETE http://localhost:8080/smartpackaging/api/smartpackages/1
Content-Type: application/json
