### REQUEST JWT TOKEN #### PRODUCTS -----------------------------
POST http://localhost:8080/smartpackaging/api/auth/login
Content-Type: application/json
Accept: application/json

{
  "username": "consumer1",
  "password": "123"
}



#### PRODUCTS ---------------------------------------------------
GET http://localhost:8080/smartpackaging/api/products/
Accept: application/json

###
POST http://localhost:8080/smartpackaging/api/products/
Content-Type: application/json

{
  "id": 1,
  "name": "postedProd",
  "date": "2020-02-03",
  "weight": 12.2,
  "ingredients": "abc dce efg"
}

###
PUT http://localhost:8080/smartpackaging/api/products/6
Content-Type: application/json

{
  "id": 7,
  "name": "updatedNammmmme",
  "date": "2033-02-03",
  "weight": 32.2,
  "ingredients": "apple silicon"
}

###
DELETE http://localhost:8080/smartpackaging/api/products/12
Content-Type: application/json



#### SMARTPACKAGES ----------------------------------------------
GET http://localhost:8080/smartpackaging/api/smartpackages/2323
Accept: application/json

###
POST http://localhost:8080/smartpackaging/api/smartpackages/
Content-Type: application/json

{
  "id": 4,
  "packType": "PRIMARY",
  "material": "cartao",
  "productId": 3
}

###
PUT http://localhost:8080/smartpackaging/api/smartpackages/1
Content-Type: application/json

{
  "id": 1,
  "packType": "SECONDARY",
  "material": "testing",
  "productId": 133,
  "currentTemperature": 40,
  "currentHumidity": 90,
  "currentAtmPressure": 80,
  "maxGForce": 10
}

###
DELETE http://localhost:8080/smartpackaging/api/smartpackages/12
Content-Type: application/json



#### ORDERS -----------------------------------------------------
GET http://localhost:8080/smartpackaging/api/orders
Accept: application/json

###
GET http://localhost:8080/smartpackaging/api/orders/2323
Accept: application/json

###
POST http://localhost:8080/smartpackaging/api/orders
Content-Type: application/json

{
  "id": 2,
  "orderDate": "2024-02-22",
  "extDeliveryDate": "2024-02-23"
}

###
PUT http://localhost:8080/smartpackaging/api/orders/32
Content-Type: application/json

{
  "id": 32,
  "orderDate": "2044-02-22",
  "extDeliveryDate": "2044-02-23"
}

###
DELETE http://localhost:8080/smartpackaging/api/orders/323
Content-Type: application/json



#### USERS ------------------------------------------------------
GET http://localhost:8080/smartpackaging/api/users
Accept: application/json

###
GET http://localhost:8080/smartpackaging/api/users/1
Accept: application/json

###
POST http://localhost:8080/smartpackaging/api/users
Content-Type: application/json

{
  "id": 4,
  "username": "user",
  "email": "user@example.com",
  "password": "user123",
  "role": "CONSUMER"
}

###
PUT http://localhost:8080/smartpackaging/api/users/3
Content-Type: application/json

{
  "id": 3,
  "username": "userUpdated",
  "email": "userUpdated@example.com",
  "password": "user123",
  "role": "CONSUMER"
}

###
DELETE http://localhost:8080/smartpackaging/api/users/3
Content-Type: application/json



#### CONSUMERS --------------------------------------------------
GET http://localhost:8080/smartpackaging/api/consumers
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJjb25zdW1lcjEiLCJpYXQiOjE3MDU3NzkwNjYsImV4cCI6MTcwNTc4MjY2Nn0.5PJnOrGVZgRoo3bpdUfTJwTvm_7OJwfF0-ERzEyK1d5Btjhovw7D_aHN3mVv7Dji

###
GET http://localhost:8080/smartpackaging/api/consumers/consumer1
Accept: application/json
Authorization: Bearer  eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJjb25zdW1lcjEiLCJpYXQiOjE3MDU3OTAwNDgsImV4cCI6MTcwNTc5MzY0OH0.OWeu-RqCoeRpExN18AgYuJWY8FdHU-HUER5D_qGvnADFnYRzX35xgd4bhoSKSr4h

###
POST http://localhost:8080/smartpackaging/api/consumers
Content-Type: application/json

{
  "id": 8,
  "username": "consumer4",
  "email": "consumer4@example.com",
  "password": "123"
}

###
PUT http://localhost:8080/smartpackaging/api/consumers/8
Content-Type: application/json

{
  "username": "consumer4Updated",
  "email": "consumer4@example.com",
  "password": "123"
}

###
DELETE http://localhost:8080/smartpackaging/api/consumers/8
Content-Type: application/json



#### OPERATORS --------------------------------------------------
GET http://localhost:8080/smartpackaging/api/operators
Accept: application/json

###
GET http://localhost:8080/smartpackaging/api/operators/10
Accept: application/json

###
POST http://localhost:8080/smartpackaging/api/operators
Content-Type: application/json

{
  "id": 13,
  "username": "operator4",
  "email": "operator4@example.com",
  "password": "123"
}

###
PUT http://localhost:8080/smartpackaging/api/operators/13
Content-Type: application/json

{
  "username": "operator4Updated",
  "email": "consumer4@example.com",
  "password": "123"
}

###
DELETE http://localhost:8080/smartpackaging/api/operators/13
Content-Type: application/json



#### PRODUCERS --------------------------------------------------
GET http://localhost:8080/smartpackaging/api/producers
Accept: application/json

###
GET http://localhost:8080/smartpackaging/api/producers/15
Accept: application/json

###
POST http://localhost:8080/smartpackaging/api/producers
Content-Type: application/json

{
  "id": 18,
  "username": "producer4",
  "email": "producer4@example.com",
  "password": "123"
}

###
PUT http://localhost:8080/smartpackaging/api/producers/18
Content-Type: application/json

{
  "username": "producer4Updated",
  "email": "producer4@example.com",
  "password": "123"
}

###
DELETE http://localhost:8080/smartpackaging/api/producers/18
Content-Type: application/json



#### TRANSPORTPACKAGES ------------------------------------------
GET http://localhost:8080/smartpackaging/api/transportpackages
Accept: application/json

###
GET http://localhost:8080/smartpackaging/api/transportpackages/133
Accept: application/json

###
POST http://localhost:8080/smartpackaging/api/transportpackages
Content-Type: application/json

{
  "id": 3,
  "currentLocation": "a chegar",
  "orderId": "2"
}

###
PUT http://localhost:8080/smartpackaging/api/transportpackages/3
Content-Type: application/json

{
  "currentLocation": "a chegar",
  "orderId": 3
}